# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'honeyKnow' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  # Pods for honeyKnow

 pod 'AFNetworking'
 pod 'Masonry'
# pod 'SDWebImage'
 pod 'MJRefresh'
 pod 'YYModel'
# pod 'MBProgressHUD'
 pod 'Toast'
 pod 'IQKeyboardManager'
 pod 'ReactiveObjC'
 pod 'TZImagePickerController'
pod 'UMCCommon'
    #pod 'UMCSecurityPlugins'
# U-Share SDK UI模块（分享面板，建议添加）
    pod 'UMCShare/UI'
    # 集成微信(精简版0.2M)
    pod 'UMCShare/Social/ReducedWeChat'
end
