# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'honeyKnow' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
   use_frameworks!

  # Pods for honeyKnow

pod 'AFNetworking'
pod 'Masonry'
pod 'SDWebImage'
pod 'MJRefresh'
pod 'YYModel'
pod 'MBProgressHUD'
pod 'Toast'
pod 'ReactiveCocoa', '~> 7.0'


end
